// Code generated by protoc-gen-go.
// source: node/node.proto
// DO NOT EDIT!

/*
Package node is a generated protocol buffer package.

It is generated from these files:
	node/node.proto

It has these top-level messages:
*/
package node

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/nathanpotter/go-chord/protos/common"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Node service

type NodeClient interface {
	Write(ctx context.Context, in *common.File, opts ...grpc.CallOption) (*common.Empty, error)
	Read(ctx context.Context, in *common.File, opts ...grpc.CallOption) (*common.File, error)
	UpdateDHT(ctx context.Context, in *common.Nodes, opts ...grpc.CallOption) (*common.Empty, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Write(ctx context.Context, in *common.File, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := grpc.Invoke(ctx, "/node.node/Write", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Read(ctx context.Context, in *common.File, opts ...grpc.CallOption) (*common.File, error) {
	out := new(common.File)
	err := grpc.Invoke(ctx, "/node.node/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) UpdateDHT(ctx context.Context, in *common.Nodes, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := grpc.Invoke(ctx, "/node.node/UpdateDHT", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Node service

type NodeServer interface {
	Write(context.Context, *common.File) (*common.Empty, error)
	Read(context.Context, *common.File) (*common.File, error)
	UpdateDHT(context.Context, *common.Nodes) (*common.Empty, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.File)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.node/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Write(ctx, req.(*common.File))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.File)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.node/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Read(ctx, req.(*common.File))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_UpdateDHT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Nodes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).UpdateDHT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.node/UpdateDHT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).UpdateDHT(ctx, req.(*common.Nodes))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "node.node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _Node_Write_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Node_Read_Handler,
		},
		{
			MethodName: "UpdateDHT",
			Handler:    _Node_UpdateDHT_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("node/node.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0xcb, 0x4f, 0x49,
	0xd5, 0x07, 0x11, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20, 0xb6, 0x94, 0x70, 0x72,
	0x7e, 0x6e, 0x6e, 0x7e, 0x9e, 0x3e, 0x84, 0x82, 0x48, 0x19, 0x35, 0x32, 0x72, 0x81, 0x65, 0x85,
	0xd4, 0xb8, 0x58, 0xc3, 0x8b, 0x32, 0x4b, 0x52, 0x85, 0x78, 0xf4, 0xa0, 0x0a, 0xdc, 0x32, 0x73,
	0x52, 0xa5, 0x78, 0x61, 0x3c, 0xd7, 0xdc, 0x82, 0x92, 0x4a, 0x25, 0x06, 0x21, 0x15, 0x2e, 0x96,
	0xa0, 0xd4, 0xc4, 0x14, 0x34, 0x65, 0x28, 0x3c, 0xa0, 0x2a, 0x6d, 0x2e, 0xce, 0xd0, 0x82, 0x94,
	0xc4, 0x92, 0x54, 0x17, 0x8f, 0x10, 0x21, 0xb8, 0x19, 0x7e, 0x40, 0x8b, 0x8a, 0x31, 0x8c, 0x4c,
	0x62, 0x03, 0x3b, 0xc5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x8c, 0x3d, 0x3c, 0xb8, 0x00,
	0x00, 0x00,
}
