// Code generated by protoc-gen-go.
// source: common/common.proto
// DO NOT EDIT!

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	common/common.proto

It has these top-level messages:
	File
	Node
	Nodes
	Empty
*/
package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type File struct {
	Name     string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
	Contents []byte `protobuf:"bytes,2,opt,name=Contents,json=contents,proto3" json:"Contents,omitempty"`
}

func (m *File) Reset()                    { *m = File{} }
func (m *File) String() string            { return proto.CompactTextString(m) }
func (*File) ProtoMessage()               {}
func (*File) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Node struct {
	Ip   string `protobuf:"bytes,1,opt,name=Ip,json=ip" json:"Ip,omitempty"`
	Port string `protobuf:"bytes,2,opt,name=Port,json=port" json:"Port,omitempty"`
	Id   uint64 `protobuf:"varint,3,opt,name=Id,json=id" json:"Id,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Nodes struct {
	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *Nodes) Reset()                    { *m = Nodes{} }
func (m *Nodes) String() string            { return proto.CompactTextString(m) }
func (*Nodes) ProtoMessage()               {}
func (*Nodes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Nodes) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*File)(nil), "common.File")
	proto.RegisterType((*Node)(nil), "common.Node")
	proto.RegisterType((*Nodes)(nil), "common.Nodes")
	proto.RegisterType((*Empty)(nil), "common.Empty")
}

func init() { proto.RegisterFile("common/common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x92,
	0x19, 0x17, 0x8b, 0x5b, 0x66, 0x4e, 0xaa, 0x90, 0x10, 0x17, 0x8b, 0x5f, 0x62, 0x6e, 0xaa, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x4b, 0x1e, 0x90, 0x2d, 0x24, 0xc5, 0xc5, 0xe1, 0x9c, 0x9f,
	0x57, 0x92, 0x9a, 0x57, 0x52, 0x2c, 0xc1, 0x04, 0x14, 0xe7, 0x09, 0xe2, 0x48, 0x86, 0xf2, 0x95,
	0xac, 0x80, 0xea, 0xf3, 0x53, 0x52, 0x85, 0xf8, 0xb8, 0x98, 0x3c, 0x0b, 0xa0, 0xba, 0x98, 0x32,
	0x0b, 0x40, 0xe6, 0x04, 0xe4, 0x17, 0x95, 0x80, 0xd5, 0x03, 0xcd, 0x29, 0x00, 0xb2, 0xc1, 0x6a,
	0x52, 0x24, 0x98, 0x81, 0x22, 0x2c, 0x40, 0x35, 0x29, 0x4a, 0xda, 0x5c, 0xac, 0x20, 0xbd, 0xc5,
	0x42, 0x4a, 0x5c, 0xac, 0x79, 0x20, 0x06, 0x50, 0x3f, 0xb3, 0x06, 0xb7, 0x11, 0x8f, 0x1e, 0xd4,
	0x89, 0x20, 0xd9, 0x20, 0x88, 0x94, 0x12, 0x3b, 0x17, 0xab, 0x6b, 0x6e, 0x41, 0x49, 0x65, 0x12,
	0x1b, 0xd8, 0xe1, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x56, 0x30, 0x6e, 0xd9, 0xcf, 0x00,
	0x00, 0x00,
}
