// Code generated by protoc-gen-go.
// source: node.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	node.proto

It has these top-level messages:
	File
	Nodes
	Empty
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type File struct {
	Name     string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
	Contents []byte `protobuf:"bytes,2,opt,name=Contents,json=contents,proto3" json:"Contents,omitempty"`
}

func (m *File) Reset()                    { *m = File{} }
func (m *File) String() string            { return proto.CompactTextString(m) }
func (*File) ProtoMessage()               {}
func (*File) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Nodes struct {
	Nodes []*Nodes_Node `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *Nodes) Reset()                    { *m = Nodes{} }
func (m *Nodes) String() string            { return proto.CompactTextString(m) }
func (*Nodes) ProtoMessage()               {}
func (*Nodes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Nodes) GetNodes() []*Nodes_Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Nodes_Node struct {
	Ip   string `protobuf:"bytes,1,opt,name=Ip,json=ip" json:"Ip,omitempty"`
	Port string `protobuf:"bytes,2,opt,name=Port,json=port" json:"Port,omitempty"`
	Id   uint64 `protobuf:"varint,3,opt,name=Id,json=id" json:"Id,omitempty"`
}

func (m *Nodes_Node) Reset()                    { *m = Nodes_Node{} }
func (m *Nodes_Node) String() string            { return proto.CompactTextString(m) }
func (*Nodes_Node) ProtoMessage()               {}
func (*Nodes_Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*File)(nil), "protos.File")
	proto.RegisterType((*Nodes)(nil), "protos.Nodes")
	proto.RegisterType((*Nodes_Node)(nil), "protos.Nodes.Node")
	proto.RegisterType((*Empty)(nil), "protos.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Node service

type NodeClient interface {
	Write(ctx context.Context, in *File, opts ...grpc.CallOption) (*Empty, error)
	Read(ctx context.Context, in *File, opts ...grpc.CallOption) (*File, error)
	UpdateDHT(ctx context.Context, in *Nodes, opts ...grpc.CallOption) (*Empty, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Write(ctx context.Context, in *File, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/protos.node/Write", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Read(ctx context.Context, in *File, opts ...grpc.CallOption) (*File, error) {
	out := new(File)
	err := grpc.Invoke(ctx, "/protos.node/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) UpdateDHT(ctx context.Context, in *Nodes, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/protos.node/UpdateDHT", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Node service

type NodeServer interface {
	Write(context.Context, *File) (*Empty, error)
	Read(context.Context, *File) (*File, error)
	UpdateDHT(context.Context, *Nodes) (*Empty, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(File)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.node/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Write(ctx, req.(*File))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(File)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.node/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Read(ctx, req.(*File))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_UpdateDHT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nodes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).UpdateDHT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.node/UpdateDHT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).UpdateDHT(ctx, req.(*Nodes))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _Node_Write_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Node_Read_Handler,
		},
		{
			MethodName: "UpdateDHT",
			Handler:    _Node_UpdateDHT_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("node.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x90, 0xbf, 0x4b, 0xc5, 0x30,
	0x10, 0xc7, 0x6d, 0x5f, 0xa2, 0xef, 0x9d, 0xef, 0x39, 0xdc, 0x54, 0x3a, 0x49, 0x10, 0x29, 0x08,
	0x1d, 0x2a, 0x38, 0xb8, 0xfa, 0x03, 0x5d, 0x8a, 0x04, 0xc5, 0xb9, 0x9a, 0x0c, 0x05, 0x9b, 0x84,
	0x26, 0x8b, 0xa3, 0xff, 0xb9, 0x97, 0xb4, 0x1d, 0xaa, 0x4b, 0x7b, 0x77, 0xf9, 0xe4, 0xfb, 0xe1,
	0x02, 0x60, 0xac, 0xd2, 0xb5, 0x1b, 0x6d, 0xb0, 0x78, 0x9c, 0x7e, 0x5e, 0xdc, 0x00, 0x7b, 0xec,
	0xbf, 0x34, 0x22, 0xb0, 0xb6, 0x1b, 0x74, 0x91, 0x9d, 0x67, 0xd5, 0x4e, 0x32, 0x43, 0x35, 0x96,
	0xb0, 0xbd, 0xb3, 0x26, 0x68, 0x13, 0x7c, 0x91, 0xd3, 0x7c, 0x2f, 0xb7, 0x9f, 0x73, 0x2f, 0x06,
	0xe0, 0x2d, 0xa5, 0x79, 0xac, 0x80, 0xc7, 0x58, 0x4f, 0x37, 0x37, 0xd5, 0x69, 0x83, 0x53, 0xbe,
	0xaf, 0xd3, 0x69, 0xfa, 0xca, 0x09, 0x28, 0x6f, 0x49, 0x41, 0x05, 0x9e, 0x41, 0xfe, 0xec, 0x66,
	0x51, 0xde, 0xbb, 0xa8, 0x7e, 0xb1, 0x63, 0x48, 0x0a, 0x52, 0x3b, 0xaa, 0x13, 0xa3, 0x8a, 0x0d,
	0x4d, 0x18, 0x31, 0x4a, 0x9c, 0x00, 0x7f, 0x18, 0x5c, 0xf8, 0x6e, 0x7e, 0x32, 0x60, 0x31, 0x0e,
	0x2f, 0x81, 0xbf, 0x8f, 0x7d, 0xd0, 0xb8, 0x5f, 0x8c, 0x71, 0x8f, 0xf2, 0xb0, 0x74, 0x09, 0x17,
	0x47, 0x78, 0x01, 0x4c, 0xea, 0x4e, 0xfd, 0xc1, 0x56, 0x1d, 0x51, 0x57, 0xb0, 0x7b, 0x73, 0xaa,
	0x0b, 0xfa, 0xfe, 0xe9, 0x15, 0x0f, 0xab, 0x1d, 0xfe, 0x45, 0x7e, 0x4c, 0x6f, 0x77, 0xfd, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0x89, 0x61, 0xff, 0x44, 0x50, 0x01, 0x00, 0x00,
}
